[package]
name = "robertshearer/grow-a-planet"
version = "0.5.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.7.0"
Promise = "evaera/promise@^4.0.0"
Signal = "sleitnick/signal@^1.5.0"
TableUtil = "sleitnick/table-util@^1.2.0"
Janitor = "howmanysmall/janitor@^1.15.0"

[dev-dependencies]
TestEZ = "roblox/testez@^0.4.1"
